# Generated by Django 2.1.1 on 2018-09-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Won Order Total')),
                ('email_address', models.EmailField(blank=250, max_length=250, verbose_name='Email Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billing_name', models.CharField(blank=True, max_length=250)),
                ('billing_address', models.CharField(blank=True, max_length=250)),
                ('bllling_city', models.CharField(blank=True, max_length=250)),
                ('billing_postcode', models.CharField(blank=True, max_length=10)),
                ('billing_country', models.CharField(blank=True, max_length=200)),
                ('shipping_name', models.CharField(blank=True, max_length=250)),
                ('shipping_address', models.CharField(blank=True, max_length=250)),
                ('shipping_city', models.CharField(blank=True, max_length=250)),
                ('shipping_postcode', models.CharField(blank=True, max_length=10)),
                ('shipping_country', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'Order',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Won Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
