# Generated by Django 2.1.1 on 2018-09-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bllling_city',
            new_name='billing_city',
        ),
    ]
