# Generated by Django 3.2.3 on 2021-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_id',
            field=models.IntegerField(default=1),
        ),
    ]
