# Generated by Django 3.2.3 on 2021-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(default='NONE', max_length=150),
        ),
    ]
