# Generated by Django 3.2.3 on 2021-05-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_orderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
