# Generated by Django 3.2.3 on 2021-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.CharField(max_length=500),
        ),
    ]
